import PDFDocument from 'pdfkit';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, BorderStyle } from 'docx';

interface ConversationItem {
    role: 'user' | 'bot';
    content: string;
    timestamp?: Date;
}

interface ExportData {
    refCode: string;
    title: string;
    status: string;
    analysis?: string;
    conversationHistory?: ConversationItem[];
    scenarios?: string; // JSON string of scenarios
}

// Clean text of all markdown and AI formatting artifacts
function cleanText(text: string): string {
    return text
        .replace(/\*\*\*/g, '')          // Bold italic
        .replace(/\*\*/g, '')            // Bold
        .replace(/\*/g, '')              // Italic
        .replace(/`{3}[\s\S]*?`{3}/g, '') // Code blocks
        .replace(/`/g, '')               // Inline code
        .replace(/#{1,6}\s/g, '')        // Headings
        .replace(/^[-*+]\s/gm, '• ')     // List bullets
        .replace(/^\d+\.\s/gm, '')       // Numbered lists
        .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1') // Links
        .replace(/^>\s/gm, '')           // Blockquotes
        .replace(/_{2,}/g, '')           // Underscores
        .replace(/~{2}/g, '')            // Strikethrough
        .replace(/\n{3,}/g, '\n\n')      // Multiple newlines
        .trim();
}

// Generate PDF export
export async function generatePDF(data: ExportData, extent: 'full' | 'analysis' | 'qa'): Promise<Buffer> {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 50 });
        const chunks: Buffer[] = [];

        doc.on('data', (chunk) => chunks.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject);

        // Header
        doc.fontSize(20).font('Helvetica-Bold').text('CASEVIEW BOT', { align: 'center' });
        doc.fontSize(16).text('Case Export Report', { align: 'center' });
        doc.moveDown();

        // Case Info
        doc.fontSize(12).font('Helvetica-Bold').text('Case Information');
        doc.fontSize(10).font('Helvetica')
            .text(`Reference: ${data.refCode}`)
            .text(`Title: ${data.title}`)
            .text(`Status: ${data.status}`)
            .text(`Generated: ${new Date().toLocaleString()}`);
        doc.moveDown();

        // Analysis Section
        if (extent === 'full' || extent === 'analysis') {
            doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
            doc.moveDown(0.5);
            doc.fontSize(14).font('Helvetica-Bold').text('ANALYSIS');
            doc.moveDown(0.5);
            doc.fontSize(10).font('Helvetica');

            if (data.analysis) {
                doc.text(cleanText(data.analysis), { align: 'left' });
            } else {
                doc.text('No analysis available.');
            }
            doc.moveDown();

            // Scenarios Section (If available)
            if (data.scenarios) {
                doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
                doc.moveDown(0.5);
                doc.fontSize(14).font('Helvetica-Bold').text('CASE SCENARIOS');
                doc.moveDown(0.5);
                doc.fontSize(10).font('Helvetica');
                doc.text(cleanText(data.scenarios), { align: 'left' });
                doc.moveDown();
            }
        }

        // Q&A Section
        if (extent === 'full' || extent === 'qa') {
            doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
            doc.moveDown(0.5);
            doc.fontSize(14).font('Helvetica-Bold').text('Q&A CONVERSATION');
            doc.moveDown(0.5);

            const history = data.conversationHistory || [];
            if (history.length > 0) {
                history.forEach((item, index) => {
                    doc.fontSize(10).font('Helvetica-Bold')
                        .fillColor(item.role === 'user' ? '#0066cc' : '#006600')
                        .text(item.role === 'user' ? 'QUESTION:' : 'ANSWER:');
                    doc.fontSize(10).font('Helvetica').fillColor('#000000')
                        .text(cleanText(item.content));
                    doc.moveDown(0.5);
                });
            } else {
                doc.fontSize(10).font('Helvetica').text('No Q&A conversation recorded.');
            }
        }

        // Footer
        doc.moveDown();
        doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
        doc.moveDown(0.5);
        doc.fontSize(8).fillColor('#666666').text('Generated by CaseView Bot', { align: 'center' });

        doc.end();
    });
}

// Generate Word/DOCX export
export async function generateWord(data: ExportData, extent: 'full' | 'analysis' | 'qa'): Promise<Buffer> {
    const sections: Paragraph[] = [];

    // Title
    sections.push(
        new Paragraph({
            text: 'CASEVIEW BOT - Case Export Report',
            heading: HeadingLevel.TITLE,
            spacing: { after: 200 }
        })
    );

    // Case Info
    sections.push(
        new Paragraph({
            text: 'Case Information',
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 200, after: 100 }
        }),
        new Paragraph({ children: [new TextRun({ text: `Reference: `, bold: true }), new TextRun(data.refCode)] }),
        new Paragraph({ children: [new TextRun({ text: `Title: `, bold: true }), new TextRun(data.title)] }),
        new Paragraph({ children: [new TextRun({ text: `Status: `, bold: true }), new TextRun(data.status)] }),
        new Paragraph({ children: [new TextRun({ text: `Generated: `, bold: true }), new TextRun(new Date().toLocaleString())] })
    );

    // Analysis Section
    if (extent === 'full' || extent === 'analysis') {
        sections.push(
            new Paragraph({
                text: 'ANALYSIS',
                heading: HeadingLevel.HEADING_1,
                spacing: { before: 400, after: 100 },
                border: { top: { style: BorderStyle.SINGLE, size: 1, color: '000000' } }
            })
        );

        if (data.analysis) {
            // Split analysis into paragraphs
            cleanText(data.analysis).split('\n\n').forEach(para => {
                if (para.trim()) {
                    sections.push(new Paragraph({ text: para.trim(), spacing: { after: 100 } }));
                }
            });
        } else {
            sections.push(new Paragraph({ text: 'No analysis available.' }));
        }

        // Scenarios Section (If available)
        if (data.scenarios) {
            sections.push(
                new Paragraph({
                    text: 'CASE SCENARIOS',
                    heading: HeadingLevel.HEADING_1,
                    spacing: { before: 400, after: 100 },
                    border: { top: { style: BorderStyle.SINGLE, size: 1, color: '000000' } }
                })
            );

            cleanText(data.scenarios).split('\n\n').forEach(para => {
                if (para.trim()) {
                    sections.push(new Paragraph({ text: para.trim(), spacing: { after: 100 } }));
                }
            });
        }
    }

    // Q&A Section
    if (extent === 'full' || extent === 'qa') {
        sections.push(
            new Paragraph({
                text: 'Q&A CONVERSATION',
                heading: HeadingLevel.HEADING_1,
                spacing: { before: 400, after: 100 },
                border: { top: { style: BorderStyle.SINGLE, size: 1, color: '000000' } }
            })
        );

        const history = data.conversationHistory || [];
        if (history.length > 0) {
            history.forEach((item, index) => {
                sections.push(
                    new Paragraph({
                        children: [
                            new TextRun({
                                text: item.role === 'user' ? 'QUESTION: ' : 'ANSWER: ',
                                bold: true,
                                color: item.role === 'user' ? '0066cc' : '006600'
                            }),
                            new TextRun(cleanText(item.content))
                        ],
                        spacing: { after: 100 }
                    })
                );
            });
        } else {
            sections.push(new Paragraph({ text: 'No Q&A conversation recorded.' }));
        }
    }

    // Footer
    sections.push(
        new Paragraph({
            children: [new TextRun({ text: 'Generated by CaseView Bot', italics: true, color: '666666' })],
            spacing: { before: 400 },
            border: { top: { style: BorderStyle.SINGLE, size: 1, color: '000000' } }
        })
    );

    const doc = new Document({
        sections: [{ properties: {}, children: sections }]
    });

    return await Packer.toBuffer(doc);
}
